"""Added total_attempted to quiz

Revision ID: 0c595f2e9f22
Revises: e478337e6a1e
Create Date: 2024-04-24 17:04:50.570769

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0c595f2e9f22'
down_revision = 'e478337e6a1e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('quiz', schema=None) as batch_op:
        batch_op.add_column(sa.Column('total_attempted', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('quiz', schema=None) as batch_op:
        batch_op.drop_column('total_attempted')

    # ### end Alembic commands ###
