"""Added total_attempted to quiz

Revision ID: 46841a92aa01
Revises: e9af7c7fcbf6
Create Date: 2024-04-24 19:21:09.199394

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '46841a92aa01'
down_revision = 'e9af7c7fcbf6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('quiz', schema=None) as batch_op:
        batch_op.alter_column('total_questions',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('total_correct',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('total_attempted',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('score',
               existing_type=sa.NUMERIC(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('quiz', schema=None) as batch_op:
        batch_op.alter_column('score',
               existing_type=sa.NUMERIC(),
               nullable=False)
        batch_op.alter_column('total_attempted',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('total_correct',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('total_questions',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
