"""Added total_correct counter to quiz

Revision ID: e478337e6a1e
Revises: 9f3f74bbf8c3
Create Date: 2024-04-24 16:17:22.511574

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e478337e6a1e'
down_revision = '9f3f74bbf8c3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('quiz', schema=None) as batch_op:
        batch_op.add_column(sa.Column('total_correct', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('quiz', schema=None) as batch_op:
        batch_op.drop_column('total_correct')

    # ### end Alembic commands ###
